from __future__ import annotations

# Compatibility facade: canonical model definitions now live in gmdg.model.*
from .model import (
    Event,
    ExternalScalarSource,
    Feature,
    FeatureNode,
    Fault,
    Fold,
    FoldedFieldParams,
    GeologicalModelGraph,
    GeologicalObservationSet,
    Id,
    InterpolatedScalarSource,
    Intrusion,
    AngularUnconformityParams,
    DisconformityParams,
    ErosionParams,
    FlatFieldParams,
    ModelSpace,
    OnlapParams,
    ParametricScalarSource,
    Region,
    Relation,
    ScalarFeature,
    ScalarSource,
    UncertaintySpec,
    Unconformity,
    Unit,
    UnitRepresentation,
    VariogramFieldParams,
)

__all__ = [
    "Id",
    "ModelSpace",
    "UncertaintySpec",
    "FlatFieldParams",
    "FoldedFieldParams",
    "VariogramFieldParams",
    "ErosionParams",
    "AngularUnconformityParams",
    "OnlapParams",
    "DisconformityParams",
    "ParametricScalarSource",
    "InterpolatedScalarSource",
    "ExternalScalarSource",
    "ScalarSource",
    "Feature",
    "ScalarFeature",
    "UnitRepresentation",
    "Unit",
    "Fault",
    "Fold",
    "Unconformity",
    "Intrusion",
    "Region",
    "FeatureNode",
    "GeologicalObservationSet",
    "Relation",
    "Event",
    "GeologicalModelGraph",
]
